CREATE SEQUENCE IF NOT EXISTS SEARCH_ID_SEQ;
CREATE TABLE IF NOT EXISTS SEARCHES (
    SEARCH_ID INTEGER DEFAULT nextval('SEARCH_ID_SEQ'),
    SEARCH_TERM VARCHAR,
    URL VARCHAR [],
    LOCATION VARCHAR [],
    REMOTE VARCHAR [],
    JOB_TYPE VARCHAR [],
    PAY VARCHAR [],
    COMPANY VARCHAR [],
    JOB_LANGUAGE VARCHAR []
    );

CREATE SEQUENCE IF NOT EXISTS JOB_ID_SEQ;
CREATE TABLE IF NOT EXISTS JOBS (
    JOB_ID INTEGER DEFAULT nextval('JOB_ID_SEQ'),
    SEARCH_ID INTEGER,
    TITLE VARCHAR,
    URL VARCHAR,
    DESCRIPTION VARCHAR,
    );